-- MySQL Script generated by MySQL Workbench
-- Mon Mar 24 20:02:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema caso1db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema caso1db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caso1db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `caso1db` ;

-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantVoiceCommands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantVoiceCommands` (
  `VoiceCommandId` INT NOT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `creationDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`VoiceCommandId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantCurrencyTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantCurrencyTypes` (
  `CurrencyTypeId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `acronym` VARCHAR(10) NOT NULL,
  `symbol` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`CurrencyTypeId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantCountries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantCountries` (
  `CountryId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `language` VARCHAR(20) NOT NULL,
  `CurrencyTypeId` INT NOT NULL,
  PRIMARY KEY (`CountryId`),
  INDEX `fk_AppAssistantCountries_AppAssistantCurrencyTypes1_idx` (`CurrencyTypeId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantCountries_AppAssistantCurrencyTypes1`
    FOREIGN KEY (`CurrencyTypeId`)
    REFERENCES `caso1db`.`AppAssistantCurrencyTypes` (`CurrencyTypeId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantUsers` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `birthdate` DATE NOT NULL,
  `role` TINYINT NOT NULL,
  `password` VARBINARY(250) NOT NULL,
  `enabled` BIT(1) NOT NULL,
  `CountryId` INT NOT NULL,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_AppAssistantUsers_AppAssistantCountries1_idx` (`CountryId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantUsers_AppAssistantCountries1`
    FOREIGN KEY (`CountryId`)
    REFERENCES `caso1db`.`AppAssistantCountries` (`CountryId`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantFileTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantFileTypes` (
  `FileTypeId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `mimeType` VARCHAR(5) NOT NULL,
  `icon` VARCHAR(200) NOT NULL,
  `enabled` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`FileTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantFiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantFiles` (
  `FileId` INT NOT NULL AUTO_INCREMENT,
  `fileName` VARCHAR(200) NOT NULL,
  `description` VARCHAR(250) NULL DEFAULT NULL,
  `fileURL` VARCHAR(200) NOT NULL,
  `deleted` BIT(1) NULL DEFAULT NULL,
  `lastupdated` DATETIME NOT NULL,
  `creation` DATETIME NOT NULL,
  `fileSize` BIGINT NOT NULL,
  `mimeType` VARCHAR(5) NOT NULL,
  `UserId` INT NOT NULL,
  `FileTypeId` INT NOT NULL,
  PRIMARY KEY (`FileId`),
  INDEX `fk_AppAssitantFiles_AppAssistanUsers1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_AppAssitantFiles_AppAssitantFileTypes1_idx` (`FileTypeId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantFiles_AppAssistanUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`),
  CONSTRAINT `fk_AppAssitantFiles_AppAssitantFileTypes1`
    FOREIGN KEY (`FileTypeId`)
    REFERENCES `caso1db`.`AppAssistantFileTypes` (`FileTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantFileUploadIARequests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantFileUploadIARequests` (
  `FileUploadIAIdRequest` INT NOT NULL AUTO_INCREMENT,
  `contentType` VARCHAR(20) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `recorderName` VARCHAR(30) NOT NULL,
  `recorderEmail` VARCHAR(80) NOT NULL,
  `requestDate` DATETIME NOT NULL,
  `FileId` INT NOT NULL,
  PRIMARY KEY (`FileUploadIAIdRequest`),
  INDEX `fk_AppAssistantFileUploadIA_AppAssistantFiles1_idx` (`FileId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantFileUploadIA_AppAssistantFiles1`
    FOREIGN KEY (`FileId`)
    REFERENCES `caso1db`.`AppAssistantFiles` (`FileId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantPrompts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantPrompts` (
  `PromptId` INT NOT NULL,
  `promptText` VARCHAR(200) NOT NULL,
  `FileUploadIAIdRequest` INT NOT NULL,
  PRIMARY KEY (`PromptId`),
  INDEX `fk_AppAssistantRequestBodies_AppAssistantFileUploadIAReques_idx` (`FileUploadIAIdRequest` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantRequestBodies_AppAssistantFileUploadIARequests1`
    FOREIGN KEY (`FileUploadIAIdRequest`)
    REFERENCES `caso1db`.`AppAssistantFileUploadIARequests` (`FileUploadIAIdRequest`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantWebHookEventTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantWebHookEventTypes` (
  `WebHookEventTypeId` INT NOT NULL,
  `eventType` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`WebHookEventTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantWebHookEventsData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantWebHookEventsData` (
  `WebHookEventDataId` INT NOT NULL AUTO_INCREMENT,
  `teamId` VARBINARY(256) NOT NULL,
  `url` VARCHAR(100) NOT NULL,
  `duration` INT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `WebHookEventTypeId` INT NOT NULL,
  `FileId` INT NOT NULL,
  PRIMARY KEY (`WebHookEventDataId`),
  INDEX `fk_AppAssistantWebHookEventsData_AppAssistantWebHookEvents1_idx` (`WebHookEventTypeId` ASC) VISIBLE,
  INDEX `fk_AppAssistantWebHookEventsData_AppAssistantFiles1_idx` (`FileId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantWebHookEventsData_AppAssistantFiles1`
    FOREIGN KEY (`FileId`)
    REFERENCES `caso1db`.`AppAssistantFiles` (`FileId`),
  CONSTRAINT `fk_AppAssistantWebHookEventsData_AppAssistantWebHookEvents1`
    FOREIGN KEY (`WebHookEventTypeId`)
    REFERENCES `caso1db`.`AppAssistantWebHookEventTypes` (`WebHookEventTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantAPIRequests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantAPIRequests` (
  `APIRequestId` BIGINT NOT NULL AUTO_INCREMENT,
  `apiURL` VARCHAR(100) NOT NULL,
  `apiToken` VARBINARY(256) NOT NULL,
  `teamId` VARBINARY(256) NOT NULL,
  `webHookURL` VARCHAR(200) NOT NULL,
  `webHookName` VARCHAR(50) NOT NULL,
  `requestDateTime` DATETIME NOT NULL,
  `status` VARCHAR(20) NULL DEFAULT NULL,
  `PromptId` INT NOT NULL,
  `WebHookEventDataId` INT NOT NULL,
  PRIMARY KEY (`APIRequestId`),
  INDEX `fk_AppAssistantAPIRequests_AppAssistantPrompts1_idx` (`PromptId` ASC) VISIBLE,
  INDEX `fk_AppAssistantAPIRequests_AppAssistantWebHookEventsData1_idx` (`WebHookEventDataId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantAPIRequests_AppAssistantPrompts1`
    FOREIGN KEY (`PromptId`)
    REFERENCES `caso1db`.`AppAssistantPrompts` (`PromptId`),
  CONSTRAINT `fk_AppAssistantAPIRequests_AppAssistantWebHookEventsData1`
    FOREIGN KEY (`WebHookEventDataId`)
    REFERENCES `caso1db`.`AppAssistantWebHookEventsData` (`WebHookEventDataId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantAPIResponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantAPIResponses` (
  `APIResponseId` INT NOT NULL AUTO_INCREMENT,
  `code` INT NOT NULL,
  `codeDescription` VARCHAR(100) NULL DEFAULT NULL,
  `responseDate` DATETIME NOT NULL,
  `APIRequestId` BIGINT NOT NULL,
  PRIMARY KEY (`APIResponseId`),
  INDEX `fk_AppAssistantAPIResponses_AppAssistantAPIRequests1_idx` (`APIRequestId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantAPIResponses_AppAssistantAPIRequests1`
    FOREIGN KEY (`APIRequestId`)
    REFERENCES `caso1db`.`AppAssistantAPIRequests` (`APIRequestId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantTasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantTasks` (
  `TaskId` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `appName` VARCHAR(30) NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `version` FLOAT NOT NULL,
  `UserId` INT NOT NULL,
  `APIResponseId` INT NOT NULL,
  PRIMARY KEY (`TaskId`),
  INDEX `fk_AppAssistantTasks_AppAssistantUsers1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_AppAssistantTasks_AppAssistantAPIResponses1_idx` (`APIResponseId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantTasks_AppAssistantAPIResponses1`
    FOREIGN KEY (`APIResponseId`)
    REFERENCES `caso1db`.`AppAssistantAPIResponses` (`APIResponseId`),
  CONSTRAINT `fk_AppAssistantTasks_AppAssistantUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantLiveChatSession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantLiveChatSession` (
  `LiveChatId` INT NOT NULL AUTO_INCREMENT,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NOT NULL,
  `status` BIT(1) NULL DEFAULT NULL,
  `appName` VARCHAR(30) NOT NULL,
  `UserId` INT NOT NULL,
  `TaskId` INT NOT NULL,
  PRIMARY KEY (`LiveChatId`),
  INDEX `fk_AppAssistantLiveChatSession_AppAssistantUsers1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_AppAssistantLiveChatSession_AppAssistantTasks1_idx` (`TaskId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantLiveChatSession_AppAssistantTasks1`
    FOREIGN KEY (`TaskId`)
    REFERENCES `caso1db`.`AppAssistantTasks` (`TaskId`),
  CONSTRAINT `fk_AppAssistantLiveChatSession_AppAssistantUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssitantAIConversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssitantAIConversation` (
  `AIConversationId` INT NOT NULL AUTO_INCREMENT,
  `startTime` DATETIME NULL DEFAULT NULL,
  `endTime` DATETIME NULL DEFAULT NULL,
  `conversationText` LONGTEXT NOT NULL,
  `title` VARCHAR(35) NULL DEFAULT NULL,
  `LiveChatId` INT NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`AIConversationId`),
  INDEX `fk_AppAssitantAIConversation_AppAssistantLiveChatSession1_idx` (`LiveChatId` ASC) VISIBLE,
  INDEX `fk_AppAssitantAIConversation_AppAssistantUsers1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantAIConversation_AppAssistantLiveChatSession1`
    FOREIGN KEY (`LiveChatId`)
    REFERENCES `caso1db`.`AppAssistantLiveChatSession` (`LiveChatId`),
  CONSTRAINT `fk_AppAssitantAIConversation_AppAssistantUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantAIMessages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantAIMessages` (
  `AIMessagesId` INT NOT NULL AUTO_INCREMENT,
  `userMessage` BIT(1) NOT NULL,
  `messageText` TINYTEXT NOT NULL,
  `sentTime` DATETIME NOT NULL,
  `processingTime` INT NOT NULL,
  `AIConversationId` INT NOT NULL,
  `VoiceCommandId` INT NOT NULL,
  PRIMARY KEY (`AIMessagesId`),
  INDEX `fk_AppAssistantAIMessages_AppAssitantAIConversation1_idx` (`AIConversationId` ASC) VISIBLE,
  INDEX `fk_AppAssistantAIMessages_AppAssistantVoiceCommands1_idx` (`VoiceCommandId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantAIMessages_AppAssistantVoiceCommands1`
    FOREIGN KEY (`VoiceCommandId`)
    REFERENCES `caso1db`.`AppAssistantVoiceCommands` (`VoiceCommandId`),
  CONSTRAINT `fk_AppAssistantAIMessages_AppAssitantAIConversation1`
    FOREIGN KEY (`AIConversationId`)
    REFERENCES `caso1db`.`AppAssitantAIConversation` (`AIConversationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantStates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantStates` (
  `StateId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `CountryId` INT NOT NULL,
  PRIMARY KEY (`StateId`),
  INDEX `fk_AppAssitantStates_AppAssitantCountries1_idx` (`CountryId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantStates_AppAssitantCountries1`
    FOREIGN KEY (`CountryId`)
    REFERENCES `caso1db`.`AppAssistantCountries` (`CountryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantCities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantCities` (
  `CityId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `StateId` INT NOT NULL,
  PRIMARY KEY (`CityId`),
  INDEX `fk_AppAssitantCities_AppAssitantStates1_idx` (`StateId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantCities_AppAssitantStates1`
    FOREIGN KEY (`StateId`)
    REFERENCES `caso1db`.`AppAssistantStates` (`StateId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantAddress` (
  `AddressId` INT NOT NULL AUTO_INCREMENT,
  `line1` VARCHAR(200) NOT NULL,
  `line2` VARCHAR(100) NULL DEFAULT NULL,
  `zipCode` VARCHAR(10) NOT NULL,
  `location` POINT NOT NULL,
  `CityId` INT NOT NULL,
  PRIMARY KEY (`AddressId`),
  INDEX `fk_AppAssitantAddress_AppAssitantCities1_idx` (`CityId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantAddress_AppAssitantCities1`
    FOREIGN KEY (`CityId`)
    REFERENCES `caso1db`.`AppAssistantCities` (`CityId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantPaymentMethods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantPaymentMethods` (
  `PaymentMethodId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `apiURL` VARCHAR(255) NULL DEFAULT NULL,
  `secreteKey` VARBINARY(255) NULL DEFAULT NULL,
  `key` VARBINARY(255) NULL DEFAULT NULL,
  `logoIconURL` VARCHAR(200) NULL DEFAULT NULL,
  `enable` BIT(1) NOT NULL,
  PRIMARY KEY (`PaymentMethodId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantDataPayments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantDataPayments` (
  `DataPaymentId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `token` VARBINARY(250) NOT NULL,
  `expToken` DATETIME NOT NULL,
  `maskAccount` VARBINARY(250) NOT NULL,
  `UserId` INT NOT NULL,
  `PaymentMethodId` INT NOT NULL,
  PRIMARY KEY (`DataPaymentId`),
  INDEX `fk_AppAssitantDataPayments_AppAssistanUsers1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_AppAssitantDataPayments_AppAssitantPaymentMethods1_idx` (`PaymentMethodId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantDataPayments_AppAssistanUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`),
  CONSTRAINT `fk_AppAssitantDataPayments_AppAssitantPaymentMethods1`
    FOREIGN KEY (`PaymentMethodId`)
    REFERENCES `caso1db`.`AppAssistantPaymentMethods` (`PaymentMethodId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantFileUploadIAResponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantFileUploadIAResponses` (
  `FileUploadIAResponseId` INT NOT NULL AUTO_INCREMENT,
  `code` INT NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `responseDate` DATETIME NOT NULL,
  `FileUploadIAIdRequest` INT NOT NULL,
  PRIMARY KEY (`FileUploadIAResponseId`),
  INDEX `fk_AppAssistantFileUploadIAResponses_AppAssistantFileUpload_idx` (`FileUploadIAIdRequest` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantFileUploadIAResponses_AppAssistantFileUploadIA1`
    FOREIGN KEY (`FileUploadIAIdRequest`)
    REFERENCES `caso1db`.`AppAssistantFileUploadIARequests` (`FileUploadIAIdRequest`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantLanguages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantLanguages` (
  `LanguagesId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NULL DEFAULT NULL,
  `culture` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`LanguagesId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantLanguagesPerCountry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantLanguagesPerCountry` (
  `LanguagePerCountryId` INT NOT NULL,
  `LanguagesId` INT NOT NULL,
  `CountryId` INT NOT NULL,
  PRIMARY KEY (`LanguagePerCountryId`),
  INDEX `fk_AppAssistantLanguagesPerCountry_AppAssitantLanguages1_idx` (`LanguagesId` ASC) VISIBLE,
  INDEX `fk_AppAssistantLanguagesPerCountry_AppAssitantCountries1_idx` (`CountryId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantLanguagesPerCountry_AppAssitantCountries1`
    FOREIGN KEY (`CountryId`)
    REFERENCES `caso1db`.`AppAssistantCountries` (`CountryId`),
  CONSTRAINT `fk_AppAssistantLanguagesPerCountry_AppAssitantLanguages1`
    FOREIGN KEY (`LanguagesId`)
    REFERENCES `caso1db`.`AppAssistantLanguages` (`LanguagesId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantTaskSteps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantTaskSteps` (
  `TaskStepId` INT NOT NULL AUTO_INCREMENT,
  `stepnum` INT NOT NULL,
  `steptype` ENUM('click', 'input', 'voice', 'wait', 'go back', 'verify') NOT NULL,
  `stepDescription` VARCHAR(300) NOT NULL,
  `expectedResult` VARCHAR(255) NOT NULL,
  `elementSelector` VARCHAR(300) NOT NULL,
  `posX` SMALLINT NULL DEFAULT NULL,
  `posY` SMALLINT NULL DEFAULT NULL,
  `inputValue` VARCHAR(255) NULL DEFAULT NULL,
  `TaskId` INT NOT NULL,
  PRIMARY KEY (`TaskStepId`),
  INDEX `fk_AppAssistantTaskSteps_AppAssistantTasks1_idx` (`TaskId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantTaskSteps_AppAssistantTasks1`
    FOREIGN KEY (`TaskId`)
    REFERENCES `caso1db`.`AppAssistantTasks` (`TaskId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantLiveChatSteps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantLiveChatSteps` (
  `LiveChatStepsId` INT NOT NULL AUTO_INCREMENT,
  `startTime` DATETIME NULL DEFAULT NULL,
  `endTime` DATETIME NULL DEFAULT NULL,
  `notes` TINYTEXT NOT NULL,
  `status` ENUM('completed', 'pending', 'go back', 'next step') NULL DEFAULT NULL,
  `LiveChatId` INT NOT NULL,
  `TaskStepId` INT NOT NULL,
  PRIMARY KEY (`LiveChatStepsId`),
  INDEX `fk_AppAssistantLiveChatSteps_AppAssistantLiveChatSession1_idx` (`LiveChatId` ASC) VISIBLE,
  INDEX `fk_AppAssistantLiveChatSteps_AppAssistantTaskSteps1_idx` (`TaskStepId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantLiveChatSteps_AppAssistantLiveChatSession1`
    FOREIGN KEY (`LiveChatId`)
    REFERENCES `caso1db`.`AppAssistantLiveChatSession` (`LiveChatId`),
  CONSTRAINT `fk_AppAssistantLiveChatSteps_AppAssistantTaskSteps1`
    FOREIGN KEY (`TaskStepId`)
    REFERENCES `caso1db`.`AppAssistantTaskSteps` (`TaskStepId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantLogSeverities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantLogSeverities` (
  `LogSeverityId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`LogSeverityId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantLogTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantLogTypes` (
  `LogTypeId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`LogTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssitantLogSources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssitantLogSources` (
  `LogSourceId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`LogSourceId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssitantCurrencyExchanges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssitantCurrencyExchanges` (
  `CurrencyExchangeId` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `exchangeRate` DECIMAL(10,2) NOT NULL,
  `enable` BIT(1) NOT NULL,
  `currentExchangeRate` BIT(1) NOT NULL,
  `CurrencyTypeId` INT NOT NULL,
  PRIMARY KEY (`CurrencyExchangeId`),
  INDEX `fk_AppAssitantCurrencyExchanges_AppAssitantCurrencyTypes1_idx` (`CurrencyTypeId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantCurrencyExchanges_AppAssitantCurrencyTypes1`
    FOREIGN KEY (`CurrencyTypeId`)
    REFERENCES `caso1db`.`AppAssistantCurrencyTypes` (`CurrencyTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantResultPayment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantResultPayment` (
  `ResultPaymentId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`ResultPaymentId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssitantPayments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssitantPayments` (
  `PaymentId` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(15,0) NOT NULL,
  `actualAmount` DECIMAL(15,0) NOT NULL,
  `currency` DECIMAL(15,0) NOT NULL,
  `auth` VARCHAR(200) NOT NULL,
  `reference` VARCHAR(200) NOT NULL,
  `chargeToken` VARBINARY(250) NOT NULL,
  `date` DATETIME NOT NULL,
  `checksum` VARBINARY(255) NOT NULL,
  `DataPaymentId` INT NOT NULL,
  `PaymentMethodId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `ResultPaymentId` INT NOT NULL,
  PRIMARY KEY (`PaymentId`),
  INDEX `fk_AppAssitantPayments_AppAssitantDataPayments1_idx` (`DataPaymentId` ASC) VISIBLE,
  INDEX `fk_AppAssitantPayments_AppAssitantPaymentMethods1_idx` (`PaymentMethodId` ASC) VISIBLE,
  INDEX `fk_AppAssitantPayments_AppAssistanUsers1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_AppAssitantPayments_AppAssistantResultPayment1_idx` (`ResultPaymentId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantPayments_AppAssistantResultPayment1`
    FOREIGN KEY (`ResultPaymentId`)
    REFERENCES `caso1db`.`AppAssistantResultPayment` (`ResultPaymentId`),
  CONSTRAINT `fk_AppAssitantPayments_AppAssistanUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`),
  CONSTRAINT `fk_AppAssitantPayments_AppAssitantDataPayments1`
    FOREIGN KEY (`DataPaymentId`)
    REFERENCES `caso1db`.`AppAssistantDataPayments` (`DataPaymentId`),
  CONSTRAINT `fk_AppAssitantPayments_AppAssitantPaymentMethods1`
    FOREIGN KEY (`PaymentMethodId`)
    REFERENCES `caso1db`.`AppAssistantPaymentMethods` (`PaymentMethodId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantTransactionsSubTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantTransactionsSubTypes` (
  `TransactionsSubTypesId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`TransactionsSubTypesId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantTransactionsTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantTransactionsTypes` (
  `TransactionTypeId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`TransactionTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantTransactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantTransactions` (
  `TransactionId` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(15,0) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `transactionDateTime` DATETIME NULL DEFAULT NULL,
  `postTime` DATETIME NULL DEFAULT NULL,
  `referenceNumber` VARCHAR(200) NULL DEFAULT NULL,
  `checkSum` VARBINARY(255) NULL DEFAULT NULL,
  `TransactionTypeId` INT NOT NULL,
  `TransactionsSubTypesId` INT NOT NULL,
  `CurrencyTypeId` INT NOT NULL,
  `PaymentId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `ExchangerateId` INT NOT NULL,
  PRIMARY KEY (`TransactionId`),
  INDEX `fk_AppAssitantTransactions_AppAssitantTransactionsTypes1_idx` (`TransactionTypeId` ASC) VISIBLE,
  INDEX `fk_AppAssitantTransactions_AppAssitantTransactionsSubTypes1_idx` (`TransactionsSubTypesId` ASC) VISIBLE,
  INDEX `fk_AppAssitantTransactions_AppAssitantCurrencyTypes1_idx` (`CurrencyTypeId` ASC) VISIBLE,
  INDEX `fk_AppAssitantTransactions_AppAssitantPayments1_idx` (`PaymentId` ASC) VISIBLE,
  INDEX `fk_AppAssitantTransactions_AppAssistanUsers1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_AppAssitantTransactions_AppAssitantCurrencyExchanges1_idx` (`ExchangerateId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantTransactions_AppAssistanUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`),
  CONSTRAINT `fk_AppAssitantTransactions_AppAssitantCurrencyExchanges1`
    FOREIGN KEY (`ExchangerateId`)
    REFERENCES `caso1db`.`AppAssitantCurrencyExchanges` (`CurrencyExchangeId`),
  CONSTRAINT `fk_AppAssitantTransactions_AppAssitantCurrencyTypes1`
    FOREIGN KEY (`CurrencyTypeId`)
    REFERENCES `caso1db`.`AppAssistantCurrencyTypes` (`CurrencyTypeId`),
  CONSTRAINT `fk_AppAssitantTransactions_AppAssitantPayments1`
    FOREIGN KEY (`PaymentId`)
    REFERENCES `caso1db`.`AppAssitantPayments` (`PaymentId`),
  CONSTRAINT `fk_AppAssitantTransactions_AppAssitantTransactionsSubTypes1`
    FOREIGN KEY (`TransactionsSubTypesId`)
    REFERENCES `caso1db`.`AppAssistantTransactionsSubTypes` (`TransactionsSubTypesId`),
  CONSTRAINT `fk_AppAssitantTransactions_AppAssitantTransactionsTypes1`
    FOREIGN KEY (`TransactionTypeId`)
    REFERENCES `caso1db`.`AppAssistantTransactionsTypes` (`TransactionTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantLogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantLogs` (
  `LogId` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NOT NULL,
  `postTime` DATETIME NOT NULL,
  `computer` VARBINARY(250) NOT NULL,
  `userName` VARCHAR(80) NOT NULL,
  `trace` VARCHAR(300) NOT NULL,
  `referenceId1` BIGINT NOT NULL,
  `referenceId2` BIGINT NOT NULL,
  `value1` VARCHAR(60) NOT NULL,
  `value2` VARCHAR(60) NOT NULL,
  `checkSum` VARBINARY(255) NOT NULL,
  `LogTypeId` INT NOT NULL,
  `LogSourceId` INT NOT NULL,
  `LogSeverityId` INT NOT NULL,
  `TransactionId` INT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`LogId`),
  INDEX `fk_AppAssitantLogs_AppAssitantLogTypes1_idx` (`LogTypeId` ASC) VISIBLE,
  INDEX `fk_AppAssitantLogs_AppAssitantLogSources1_idx` (`LogSourceId` ASC) VISIBLE,
  INDEX `fk_AppAssitantLogs_AppAssitantLogSeverities1_idx` (`LogSeverityId` ASC) VISIBLE,
  INDEX `fk_AppAssitantLogs_AppAssitantTransactions1_idx` (`TransactionId` ASC) VISIBLE,
  INDEX `fk_AppAssitantLogs_AppAssistanUsers1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantLogs_AppAssistanUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`),
  CONSTRAINT `fk_AppAssitantLogs_AppAssitantLogSeverities1`
    FOREIGN KEY (`LogSeverityId`)
    REFERENCES `caso1db`.`AppAssistantLogSeverities` (`LogSeverityId`),
  CONSTRAINT `fk_AppAssitantLogs_AppAssitantLogSources1`
    FOREIGN KEY (`LogSourceId`)
    REFERENCES `caso1db`.`AppAssitantLogSources` (`LogSourceId`),
  CONSTRAINT `fk_AppAssitantLogs_AppAssitantLogTypes1`
    FOREIGN KEY (`LogTypeId`)
    REFERENCES `caso1db`.`AppAssistantLogTypes` (`LogTypeId`),
  CONSTRAINT `fk_AppAssitantLogs_AppAssitantTransactions1`
    FOREIGN KEY (`TransactionId`)
    REFERENCES `caso1db`.`AppAssistantTransactions` (`TransactionId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantMediaAnalysisOptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantMediaAnalysisOptions` (
  `MediaAnalysisOptionId` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL,
  `PromptId` INT NOT NULL,
  PRIMARY KEY (`MediaAnalysisOptionId`),
  INDEX `fk_AppAssistantMediaAnalysisOptions_AppAssistantPrompts1_idx` (`PromptId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantMediaAnalysisOptions_AppAssistantPrompts1`
    FOREIGN KEY (`PromptId`)
    REFERENCES `caso1db`.`AppAssistantPrompts` (`PromptId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantMouseEvents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantMouseEvents` (
  `MouseEventId` INT NOT NULL AUTO_INCREMENT,
  `eventName` VARCHAR(30) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`MouseEventId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssitantRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssitantRoles` (
  `RoleId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(300) NULL DEFAULT NULL,
  `updated` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`RoleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantRolesPerUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantRolesPerUser` (
  `RolePerUserId` INT NOT NULL,
  `UserId` INT NOT NULL,
  `RoleId` INT NOT NULL,
  `update` DATETIME NOT NULL,
  `enabled` BIT(1) NOT NULL,
  PRIMARY KEY (`RolePerUserId`),
  INDEX `fk_AppAssistantRolesPerUser_AppAssistanUsers1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_AppAssistantRolesPerUser_AppAssitantRoles1_idx` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantRolesPerUser_AppAssistanUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`),
  CONSTRAINT `fk_AppAssistantRolesPerUser_AppAssitantRoles1`
    FOREIGN KEY (`RoleId`)
    REFERENCES `caso1db`.`AppAssitantRoles` (`RoleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantSchedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantSchedules` (
  `ScheduleId` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `repeat` ENUM('biweekly', 'mothly', 'yearly') NOT NULL,
  `endType` VARCHAR(45) NULL DEFAULT NULL,
  `repetitionsl` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ScheduleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantScheduleDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantScheduleDetails` (
  `ScheduleDetailId` INT NOT NULL,
  `deleted` BIT(1) NOT NULL,
  `baseDate` DATETIME NOT NULL,
  `lastExecution` DATETIME NOT NULL,
  `NextExecution` DATETIME NOT NULL,
  `ScheduleId` INT NOT NULL,
  PRIMARY KEY (`ScheduleDetailId`),
  INDEX `fk_AppAssistantScheduleDetails_AppAssistantSchedules1_idx` (`ScheduleId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantScheduleDetails_AppAssistantSchedules1`
    FOREIGN KEY (`ScheduleId`)
    REFERENCES `caso1db`.`AppAssistantSchedules` (`ScheduleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantScreenRecordingsMouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantScreenRecordingsMouse` (
  `ScreenRecordingMouseId` INT NOT NULL AUTO_INCREMENT,
  `startTime` TIME NOT NULL,
  `finishTime` TIME NOT NULL,
  `posX` SMALLINT NOT NULL,
  `posY` SMALLINT NOT NULL,
  `MouseEventId` INT NOT NULL,
  PRIMARY KEY (`ScreenRecordingMouseId`),
  INDEX `fk_AppAssistantScreenRecordingsMouse_AppAssistantMouseEvent_idx` (`MouseEventId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantScreenRecordingsMouse_AppAssistantMouseEvents1`
    FOREIGN KEY (`MouseEventId`)
    REFERENCES `caso1db`.`AppAssistantMouseEvents` (`MouseEventId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantScreenRecordings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantScreenRecordings` (
  `ScreenRecordingId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `createDate` DATETIME NOT NULL,
  `size` BIGINT NOT NULL,
  `duration` TIME NOT NULL,
  `ScreenRecordingMouseId` INT NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`ScreenRecordingId`),
  INDEX `fk_AppAssistantScreenRecordings_AppAssistantScreenRecording_idx` (`ScreenRecordingMouseId` ASC) VISIBLE,
  INDEX `fk_AppAssistantScreenRecordings_AppAssistantUsers1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantScreenRecordings_AppAssistantScreenRecordingsM1`
    FOREIGN KEY (`ScreenRecordingMouseId`)
    REFERENCES `caso1db`.`AppAssistantScreenRecordingsMouse` (`ScreenRecordingMouseId`),
  CONSTRAINT `fk_AppAssistantScreenRecordings_AppAssistantUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantSuscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantSuscriptions` (
  `SuscriptionsId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `logoURL` VARCHAR(200) NULL DEFAULT NULL,
  `enable` BIT(1) NOT NULL,
  PRIMARY KEY (`SuscriptionsId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssitantSuscriptionPrices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssitantSuscriptionPrices` (
  `SuscriptionPricesId` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NOT NULL,
  `postTime` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `update` DATETIME NOT NULL,
  `SuscriptionsId` INT NOT NULL,
  `CurrencyTypeId` INT NOT NULL,
  PRIMARY KEY (`SuscriptionPricesId`),
  INDEX `fk_AppAssitantSuscriptionPrices_AppAssitantSuscriptions1_idx` (`SuscriptionsId` ASC) VISIBLE,
  INDEX `fk_AppAssitantSuscriptionPrices_AppAssitantCurrencyTypes1_idx` (`CurrencyTypeId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantSuscriptionPrices_AppAssitantCurrencyTypes1`
    FOREIGN KEY (`CurrencyTypeId`)
    REFERENCES `caso1db`.`AppAssistantCurrencyTypes` (`CurrencyTypeId`),
  CONSTRAINT `fk_AppAssitantSuscriptionPrices_AppAssitantSuscriptions1`
    FOREIGN KEY (`SuscriptionsId`)
    REFERENCES `caso1db`.`AppAssistantSuscriptions` (`SuscriptionsId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantSuscriptionSchedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantSuscriptionSchedules` (
  `AppAssistantSuscriptionSchedulesId` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATETIME NOT NULL,
  `status` BIT(1) NOT NULL,
  `SuscriptionsId` INT NOT NULL,
  `SuscriptionPricesId` INT NOT NULL,
  `ScheduleId` INT NOT NULL,
  PRIMARY KEY (`AppAssistantSuscriptionSchedulesId`),
  INDEX `fk_AppAssistantSuscriptionSchedules_AppAssitantSuscriptions_idx` (`SuscriptionsId` ASC) VISIBLE,
  INDEX `fk_AppAssistantSuscriptionSchedules_AppAssitantSuscriptionP_idx` (`SuscriptionPricesId` ASC) VISIBLE,
  INDEX `fk_AppAssistantSuscriptionSchedules_AppAssistantSchedules1_idx` (`ScheduleId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantSuscriptionSchedules_AppAssistantSchedules1`
    FOREIGN KEY (`ScheduleId`)
    REFERENCES `caso1db`.`AppAssistantSchedules` (`ScheduleId`),
  CONSTRAINT `fk_AppAssistantSuscriptionSchedules_AppAssitantSuscriptionPri1`
    FOREIGN KEY (`SuscriptionPricesId`)
    REFERENCES `caso1db`.`AppAssitantSuscriptionPrices` (`SuscriptionPricesId`),
  CONSTRAINT `fk_AppAssistantSuscriptionSchedules_AppAssitantSuscriptions1`
    FOREIGN KEY (`SuscriptionsId`)
    REFERENCES `caso1db`.`AppAssistantSuscriptions` (`SuscriptionsId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantTranscriptSegments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantTranscriptSegments` (
  `TranscriptSegmentId` INT NOT NULL AUTO_INCREMENT,
  `MediaAnalysisOptionId` INT NOT NULL,
  `start` INT NOT NULL,
  `end` INT NOT NULL,
  PRIMARY KEY (`TranscriptSegmentId`),
  INDEX `fk_AppAssistantTranscriptSegments_AppAssistantMediaAnalysis_idx` (`MediaAnalysisOptionId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantTranscriptSegments_AppAssistantMediaAnalysisOp1`
    FOREIGN KEY (`MediaAnalysisOptionId`)
    REFERENCES `caso1db`.`AppAssistantMediaAnalysisOptions` (`MediaAnalysisOptionId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantTranslations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantTranslations` (
  `TranslationsId` INT NOT NULL AUTO_INCREMENT,
  `LanguagesId` INT NOT NULL,
  PRIMARY KEY (`TranslationsId`),
  INDEX `fk_AppAssitantTranslations_AppAssitantLanguages1_idx` (`LanguagesId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantTranslations_AppAssitantLanguages1`
    FOREIGN KEY (`LanguagesId`)
    REFERENCES `caso1db`.`AppAssistantLanguages` (`LanguagesId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssistantUserAddresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssistantUserAddresses` (
  `UserAddressId` INT NOT NULL,
  `AddressId` INT NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`UserAddressId`),
  INDEX `fk_AppAssistantUserAddresses_AppAssitantAddress1_idx` (`AddressId` ASC) VISIBLE,
  INDEX `fk_AppAssistantUserAddresses_AppAssistanUsers1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssistantUserAddresses_AppAssistanUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`),
  CONSTRAINT `fk_AppAssistantUserAddresses_AppAssitantAddress1`
    FOREIGN KEY (`AddressId`)
    REFERENCES `caso1db`.`AppAssistantAddress` (`AddressId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssitantPlanFeatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssitantPlanFeatures` (
  `PlanFeatureId` INT NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `enable` BIT(1) NULL DEFAULT NULL,
  `dataType` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`PlanFeatureId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssitantFeaturePerPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssitantFeaturePerPlan` (
  `FeaturePerPlanId` INT NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `enable` BIT(1) NOT NULL,
  `PlanFeatureId` INT NOT NULL,
  `SuscriptionsId` INT NOT NULL,
  PRIMARY KEY (`FeaturePerPlanId`),
  INDEX `fk_AppAssitantFeaturePerPlan_AppAssitantPlanFeatures1_idx` (`PlanFeatureId` ASC) VISIBLE,
  INDEX `fk_AppAssitantFeaturePerPlan_AppAssitantSuscriptions1_idx` (`SuscriptionsId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantFeaturePerPlan_AppAssitantPlanFeatures1`
    FOREIGN KEY (`PlanFeatureId`)
    REFERENCES `caso1db`.`AppAssitantPlanFeatures` (`PlanFeatureId`),
  CONSTRAINT `fk_AppAssitantFeaturePerPlan_AppAssitantSuscriptions1`
    FOREIGN KEY (`SuscriptionsId`)
    REFERENCES `caso1db`.`AppAssistantSuscriptions` (`SuscriptionsId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssitantPermissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssitantPermissions` (
  `PermissionId` INT NOT NULL AUTO_INCREMENT,
  `permissionName` VARCHAR(100) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`PermissionId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssitantRolePermissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssitantRolePermissions` (
  `RolePermissionId` INT NOT NULL AUTO_INCREMENT,
  `PermissionId` INT NOT NULL,
  `RoleId` INT NOT NULL,
  PRIMARY KEY (`RolePermissionId`),
  INDEX `fk_AppAssitantRolePermissions_AppAssitantPermissions1_idx` (`PermissionId` ASC) VISIBLE,
  INDEX `fk_AppAssitantRolePermissions_AppAssitantRoles1_idx` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantRolePermissions_AppAssitantPermissions1`
    FOREIGN KEY (`PermissionId`)
    REFERENCES `caso1db`.`AppAssitantPermissions` (`PermissionId`),
  CONSTRAINT `fk_AppAssitantRolePermissions_AppAssitantRoles1`
    FOREIGN KEY (`RoleId`)
    REFERENCES `caso1db`.`AppAssitantRoles` (`RoleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caso1db`.`AppAssitantSuscriptionUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caso1db`.`AppAssitantSuscriptionUser` (
  `SuscriptionUserId` INT NOT NULL AUTO_INCREMENT,
  `UserId` INT NOT NULL,
  `SuscriptionPricesId` INT NOT NULL,
  `enable` BIT(1) NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  PRIMARY KEY (`SuscriptionUserId`),
  INDEX `fk_AppAssitantSuscriptionUser_AppAssistanUsers1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_AppAssitantSuscriptionUser_AppAssitantSuscriptionPrices1_idx` (`SuscriptionPricesId` ASC) VISIBLE,
  CONSTRAINT `fk_AppAssitantSuscriptionUser_AppAssistanUsers1`
    FOREIGN KEY (`UserId`)
    REFERENCES `caso1db`.`AppAssistantUsers` (`UserId`),
  CONSTRAINT `fk_AppAssitantSuscriptionUser_AppAssitantSuscriptionPrices1`
    FOREIGN KEY (`SuscriptionPricesId`)
    REFERENCES `caso1db`.`AppAssitantSuscriptionPrices` (`SuscriptionPricesId`))
ENGINE = InnoDB
AUTO_INCREMENT = 152
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `caso1db` ;

-- -----------------------------------------------------
-- procedure FillSuscriptionUser
-- -----------------------------------------------------

DELIMITER $$
USE `caso1db`$$
CREATE DEFINER=`root`@`%` PROCEDURE `FillSuscriptionUser`()
BEGIN
	SET @SuscriptionCounter = 150;

	WHILE @SuscriptionCounter > 0 DO

		-- Generar una fecha y hora aleatoria dentro del rango especificado
		set @startDate = DATE_ADD('2023-01-01 00:00:00', INTERVAL floor(rand() * 3) YEAR);
        set @startDate = DATE_ADD(@startDate, INTERVAL floor(1 + rand() * 12) month);
		set @startDate = DATE_ADD(@startDate, INTERVAL floor(1 + rand() * DAY(LAST_DAY(@startDate))) day);
		set @startDate = DATE_ADD(@startDate, INTERVAL floor(rand() * 24) hour);
		set @startDate = DATE_ADD(@startDate, INTERVAL floor(rand() * 60) minute);
		set @startDate = DATE_ADD(@startDate, INTERVAL floor(rand() * 60) second);
        
		set @endDate = DATE_ADD(@startDate, INTERVAL floor(1 + rand() * 12) month);
		set @endDate = DATE_ADD(@endDate, INTERVAL floor(1 + rand() * DAY(LAST_DAY(@endDate))) day);
		set @endDate = DATE_ADD(@endDate, INTERVAL floor(rand() * 24) hour);
		set @endDate = DATE_ADD(@endDate, INTERVAL floor(rand() * 60) minute);
		set @endDate = DATE_ADD(@endDate, INTERVAL floor(rand() * 60) second);
        
		SET @UserId = FLOOR(1 + RAND() * 50); -- Genera un numero aleatorio entre 81 y 130;
        SET @SuscriptionPricesId = FLOOR(1 + RAND() * 3);
        SET @`Enable` = FLOOR(RAND() * 2);
        
        
		INSERT INTO AppAssitantSuscriptionUser(UserId, SuscriptionPricesId, `enable`, startDate, endDate)
		VALUES (@UserId, @SuscriptionPricesId, @`Enable`, @startDate, @endDate);
		
        
		SET @SuscriptionCounter = @SuscriptionCounter - 1;
	END WHILE ;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure FillUsers
-- -----------------------------------------------------

DELIMITER $$
USE `caso1db`$$
CREATE DEFINER=`root`@`%` PROCEDURE `FillUsers`()
BEGIN
	SET @countUsers = 50;

	WHILE @countUsers > 0 DO

		-- Declarar la variable para almacenar la fecha aleatoria
		SET @birthdate = NULL;
		-- Generar una fecha y hora aleatoria dentro del rango especificado
		SET @birthdate = DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 40) YEAR); -- Fecha aleatoria en los últimos 40 años



		SET @nombre = NULL;
		SET @lastname = NULL;
        SET @email = NULL;
        SET @countryId = NULL;
		SET @typeEmail= NULL;
        SET @pass_word = FLOOR(1 + RAND() * 1000000);
        SET @countryId = FLOOR(1 + RAND() * 3);
		SELECT ELT(FLOOR(1 + RAND() * 10), 'Andres', 'Christopher', 'Carlos', 'Ariel', 'Diego', 'Rodrigo', 'Luis', 'Jose', 'Adrian', 'Juan') INTO @nombre;
		SELECT ELT(FLOOR(1 + RAND() * 10), 'Baldi', 'Mora', 'Venegas', 'Rodriguez', 'Vargas', 'Abarca', 'Cespedes', 'Castillo', 'Sanches', 'Hernandez','Benavides') INTO @lastname;
		SELECT ELT(FLOOR(1 + RAND() * 5), '@gmail.com', '@hotmail.com', '@yahoo.es', '@outlook.es', 'outlook.com') INTO @typeEmail;
		
        SET @email = CONCAT(LOWER(@nombre), '.', LOWER(@lastname), @pass_word,  @typeEmail);
        
        
		INSERT INTO AppAssistantUsers(email, firstname, lastname, birthdate, `role`, `password`, `enabled`, CountryId)
		VALUES (@email, @nombre, @lastname, @birthdate, 1, @pass_word, 1, @countryId);
		
        
		SET @countUsers = @countUsers - 1;
	END WHILE ;
END$$

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
